/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TahminTakibiRouteImport } from './routes/tahmin-takibi'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as OosRouteImport } from './routes/oos'
import { Route as ModelHealthRouteImport } from './routes/model-health'
import { Route as MlLabRouteImport } from './routes/ml-lab'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MarketIntelligenceRouteImport } from './routes/market-intelligence'
import { Route as FirsatlarRouteImport } from './routes/firsatlar'
import { Route as FeatureImportanceRouteImport } from './routes/feature-importance'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EnsembleLabRouteImport } from './routes/ensemble-lab'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as BacktestLabRouteImport } from './routes/backtest-lab'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AiPatternsRouteImport } from './routes/ai-patterns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HisseSymbolRouteImport } from './routes/hisse.$symbol'
import { Route as ApiPublicPredictionsRouteImport } from './routes/api/public/predictions'
import { Route as ApiPublicLiveMoversRouteImport } from './routes/api/public/live-movers'
import { Route as ApiPublicIngestOhlcRouteImport } from './routes/api/public/ingest-ohlc'
import { Route as ApiPublicIngestNewsRouteImport } from './routes/api/public/ingest-news'
import { Route as ApiPublicIngestMacroRouteImport } from './routes/api/public/ingest-macro'
import { Route as ApiPublicHooksWeeklyRetrainRouteImport } from './routes/api/public/hooks/weekly-retrain'
import { Route as ApiPublicHooksDailyAuditRouteImport } from './routes/api/public/hooks/daily-audit'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TahminTakibiRoute = TahminTakibiRouteImport.update({
  id: '/tahmin-takibi',
  path: '/tahmin-takibi',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const OosRoute = OosRouteImport.update({
  id: '/oos',
  path: '/oos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelHealthRoute = ModelHealthRouteImport.update({
  id: '/model-health',
  path: '/model-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MlLabRoute = MlLabRouteImport.update({
  id: '/ml-lab',
  path: '/ml-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceRoute = MarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FirsatlarRoute = FirsatlarRouteImport.update({
  id: '/firsatlar',
  path: '/firsatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureImportanceRoute = FeatureImportanceRouteImport.update({
  id: '/feature-importance',
  path: '/feature-importance',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsembleLabRoute = EnsembleLabRouteImport.update({
  id: '/ensemble-lab',
  path: '/ensemble-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestLabRoute = BacktestLabRouteImport.update({
  id: '/backtest-lab',
  path: '/backtest-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPatternsRoute = AiPatternsRouteImport.update({
  id: '/ai-patterns',
  path: '/ai-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HisseSymbolRoute = HisseSymbolRouteImport.update({
  id: '/hisse/$symbol',
  path: '/hisse/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPredictionsRoute = ApiPublicPredictionsRouteImport.update({
  id: '/api/public/predictions',
  path: '/api/public/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveMoversRoute = ApiPublicLiveMoversRouteImport.update({
  id: '/api/public/live-movers',
  path: '/api/public/live-movers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestOhlcRoute = ApiPublicIngestOhlcRouteImport.update({
  id: '/api/public/ingest-ohlc',
  path: '/api/public/ingest-ohlc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestNewsRoute = ApiPublicIngestNewsRouteImport.update({
  id: '/api/public/ingest-news',
  path: '/api/public/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestMacroRoute = ApiPublicIngestMacroRouteImport.update({
  id: '/api/public/ingest-macro',
  path: '/api/public/ingest-macro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyRetrainRoute =
  ApiPublicHooksWeeklyRetrainRouteImport.update({
    id: '/api/public/hooks/weekly-retrain',
    path: '/api/public/hooks/weekly-retrain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyAuditRoute =
  ApiPublicHooksDailyAuditRouteImport.update({
    id: '/api/public/hooks/daily-audit',
    path: '/api/public/hooks/daily-audit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-patterns': typeof AiPatternsRoute
  '/backtest': typeof BacktestRoute
  '/backtest-lab': typeof BacktestLabRoute
  '/coverage': typeof CoverageRoute
  '/ensemble-lab': typeof EnsembleLabRoute
  '/events': typeof EventsRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/firsatlar': typeof FirsatlarRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/methodology': typeof MethodologyRoute
  '/ml-lab': typeof MlLabRoute
  '/model-health': typeof ModelHealthRoute
  '/oos': typeof OosRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/tahmin-takibi': typeof TahminTakibiRoute
  '/watchlist': typeof WatchlistRoute
  '/hisse/$symbol': typeof HisseSymbolRoute
  '/api/public/ingest-macro': typeof ApiPublicIngestMacroRoute
  '/api/public/ingest-news': typeof ApiPublicIngestNewsRoute
  '/api/public/ingest-ohlc': typeof ApiPublicIngestOhlcRoute
  '/api/public/live-movers': typeof ApiPublicLiveMoversRoute
  '/api/public/predictions': typeof ApiPublicPredictionsRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/weekly-retrain': typeof ApiPublicHooksWeeklyRetrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-patterns': typeof AiPatternsRoute
  '/backtest': typeof BacktestRoute
  '/backtest-lab': typeof BacktestLabRoute
  '/coverage': typeof CoverageRoute
  '/ensemble-lab': typeof EnsembleLabRoute
  '/events': typeof EventsRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/firsatlar': typeof FirsatlarRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/methodology': typeof MethodologyRoute
  '/ml-lab': typeof MlLabRoute
  '/model-health': typeof ModelHealthRoute
  '/oos': typeof OosRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/tahmin-takibi': typeof TahminTakibiRoute
  '/watchlist': typeof WatchlistRoute
  '/hisse/$symbol': typeof HisseSymbolRoute
  '/api/public/ingest-macro': typeof ApiPublicIngestMacroRoute
  '/api/public/ingest-news': typeof ApiPublicIngestNewsRoute
  '/api/public/ingest-ohlc': typeof ApiPublicIngestOhlcRoute
  '/api/public/live-movers': typeof ApiPublicLiveMoversRoute
  '/api/public/predictions': typeof ApiPublicPredictionsRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/weekly-retrain': typeof ApiPublicHooksWeeklyRetrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-patterns': typeof AiPatternsRoute
  '/backtest': typeof BacktestRoute
  '/backtest-lab': typeof BacktestLabRoute
  '/coverage': typeof CoverageRoute
  '/ensemble-lab': typeof EnsembleLabRoute
  '/events': typeof EventsRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/firsatlar': typeof FirsatlarRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/methodology': typeof MethodologyRoute
  '/ml-lab': typeof MlLabRoute
  '/model-health': typeof ModelHealthRoute
  '/oos': typeof OosRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/tahmin-takibi': typeof TahminTakibiRoute
  '/watchlist': typeof WatchlistRoute
  '/hisse/$symbol': typeof HisseSymbolRoute
  '/api/public/ingest-macro': typeof ApiPublicIngestMacroRoute
  '/api/public/ingest-news': typeof ApiPublicIngestNewsRoute
  '/api/public/ingest-ohlc': typeof ApiPublicIngestOhlcRoute
  '/api/public/live-movers': typeof ApiPublicLiveMoversRoute
  '/api/public/predictions': typeof ApiPublicPredictionsRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/weekly-retrain': typeof ApiPublicHooksWeeklyRetrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-patterns'
    | '/backtest'
    | '/backtest-lab'
    | '/coverage'
    | '/ensemble-lab'
    | '/events'
    | '/feature-importance'
    | '/firsatlar'
    | '/market-intelligence'
    | '/methodology'
    | '/ml-lab'
    | '/model-health'
    | '/oos'
    | '/signals'
    | '/sitemap.xml'
    | '/stocks'
    | '/tahmin-takibi'
    | '/watchlist'
    | '/hisse/$symbol'
    | '/api/public/ingest-macro'
    | '/api/public/ingest-news'
    | '/api/public/ingest-ohlc'
    | '/api/public/live-movers'
    | '/api/public/predictions'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/weekly-retrain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-patterns'
    | '/backtest'
    | '/backtest-lab'
    | '/coverage'
    | '/ensemble-lab'
    | '/events'
    | '/feature-importance'
    | '/firsatlar'
    | '/market-intelligence'
    | '/methodology'
    | '/ml-lab'
    | '/model-health'
    | '/oos'
    | '/signals'
    | '/sitemap.xml'
    | '/stocks'
    | '/tahmin-takibi'
    | '/watchlist'
    | '/hisse/$symbol'
    | '/api/public/ingest-macro'
    | '/api/public/ingest-news'
    | '/api/public/ingest-ohlc'
    | '/api/public/live-movers'
    | '/api/public/predictions'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/weekly-retrain'
  id:
    | '__root__'
    | '/'
    | '/ai-patterns'
    | '/backtest'
    | '/backtest-lab'
    | '/coverage'
    | '/ensemble-lab'
    | '/events'
    | '/feature-importance'
    | '/firsatlar'
    | '/market-intelligence'
    | '/methodology'
    | '/ml-lab'
    | '/model-health'
    | '/oos'
    | '/signals'
    | '/sitemap.xml'
    | '/stocks'
    | '/tahmin-takibi'
    | '/watchlist'
    | '/hisse/$symbol'
    | '/api/public/ingest-macro'
    | '/api/public/ingest-news'
    | '/api/public/ingest-ohlc'
    | '/api/public/live-movers'
    | '/api/public/predictions'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/weekly-retrain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPatternsRoute: typeof AiPatternsRoute
  BacktestRoute: typeof BacktestRoute
  BacktestLabRoute: typeof BacktestLabRoute
  CoverageRoute: typeof CoverageRoute
  EnsembleLabRoute: typeof EnsembleLabRoute
  EventsRoute: typeof EventsRoute
  FeatureImportanceRoute: typeof FeatureImportanceRoute
  FirsatlarRoute: typeof FirsatlarRoute
  MarketIntelligenceRoute: typeof MarketIntelligenceRoute
  MethodologyRoute: typeof MethodologyRoute
  MlLabRoute: typeof MlLabRoute
  ModelHealthRoute: typeof ModelHealthRoute
  OosRoute: typeof OosRoute
  SignalsRoute: typeof SignalsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StocksRoute: typeof StocksRoute
  TahminTakibiRoute: typeof TahminTakibiRoute
  WatchlistRoute: typeof WatchlistRoute
  HisseSymbolRoute: typeof HisseSymbolRoute
  ApiPublicIngestMacroRoute: typeof ApiPublicIngestMacroRoute
  ApiPublicIngestNewsRoute: typeof ApiPublicIngestNewsRoute
  ApiPublicIngestOhlcRoute: typeof ApiPublicIngestOhlcRoute
  ApiPublicLiveMoversRoute: typeof ApiPublicLiveMoversRoute
  ApiPublicPredictionsRoute: typeof ApiPublicPredictionsRoute
  ApiPublicHooksDailyAuditRoute: typeof ApiPublicHooksDailyAuditRoute
  ApiPublicHooksWeeklyRetrainRoute: typeof ApiPublicHooksWeeklyRetrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahmin-takibi': {
      id: '/tahmin-takibi'
      path: '/tahmin-takibi'
      fullPath: '/tahmin-takibi'
      preLoaderRoute: typeof TahminTakibiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oos': {
      id: '/oos'
      path: '/oos'
      fullPath: '/oos'
      preLoaderRoute: typeof OosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-health': {
      id: '/model-health'
      path: '/model-health'
      fullPath: '/model-health'
      preLoaderRoute: typeof ModelHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-lab': {
      id: '/ml-lab'
      path: '/ml-lab'
      fullPath: '/ml-lab'
      preLoaderRoute: typeof MlLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence': {
      id: '/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof MarketIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firsatlar': {
      id: '/firsatlar'
      path: '/firsatlar'
      fullPath: '/firsatlar'
      preLoaderRoute: typeof FirsatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-importance': {
      id: '/feature-importance'
      path: '/feature-importance'
      fullPath: '/feature-importance'
      preLoaderRoute: typeof FeatureImportanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensemble-lab': {
      id: '/ensemble-lab'
      path: '/ensemble-lab'
      fullPath: '/ensemble-lab'
      preLoaderRoute: typeof EnsembleLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest-lab': {
      id: '/backtest-lab'
      path: '/backtest-lab'
      fullPath: '/backtest-lab'
      preLoaderRoute: typeof BacktestLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-patterns': {
      id: '/ai-patterns'
      path: '/ai-patterns'
      fullPath: '/ai-patterns'
      preLoaderRoute: typeof AiPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisse/$symbol': {
      id: '/hisse/$symbol'
      path: '/hisse/$symbol'
      fullPath: '/hisse/$symbol'
      preLoaderRoute: typeof HisseSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/predictions': {
      id: '/api/public/predictions'
      path: '/api/public/predictions'
      fullPath: '/api/public/predictions'
      preLoaderRoute: typeof ApiPublicPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-movers': {
      id: '/api/public/live-movers'
      path: '/api/public/live-movers'
      fullPath: '/api/public/live-movers'
      preLoaderRoute: typeof ApiPublicLiveMoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-ohlc': {
      id: '/api/public/ingest-ohlc'
      path: '/api/public/ingest-ohlc'
      fullPath: '/api/public/ingest-ohlc'
      preLoaderRoute: typeof ApiPublicIngestOhlcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-news': {
      id: '/api/public/ingest-news'
      path: '/api/public/ingest-news'
      fullPath: '/api/public/ingest-news'
      preLoaderRoute: typeof ApiPublicIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-macro': {
      id: '/api/public/ingest-macro'
      path: '/api/public/ingest-macro'
      fullPath: '/api/public/ingest-macro'
      preLoaderRoute: typeof ApiPublicIngestMacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-retrain': {
      id: '/api/public/hooks/weekly-retrain'
      path: '/api/public/hooks/weekly-retrain'
      fullPath: '/api/public/hooks/weekly-retrain'
      preLoaderRoute: typeof ApiPublicHooksWeeklyRetrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-audit': {
      id: '/api/public/hooks/daily-audit'
      path: '/api/public/hooks/daily-audit'
      fullPath: '/api/public/hooks/daily-audit'
      preLoaderRoute: typeof ApiPublicHooksDailyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPatternsRoute: AiPatternsRoute,
  BacktestRoute: BacktestRoute,
  BacktestLabRoute: BacktestLabRoute,
  CoverageRoute: CoverageRoute,
  EnsembleLabRoute: EnsembleLabRoute,
  EventsRoute: EventsRoute,
  FeatureImportanceRoute: FeatureImportanceRoute,
  FirsatlarRoute: FirsatlarRoute,
  MarketIntelligenceRoute: MarketIntelligenceRoute,
  MethodologyRoute: MethodologyRoute,
  MlLabRoute: MlLabRoute,
  ModelHealthRoute: ModelHealthRoute,
  OosRoute: OosRoute,
  SignalsRoute: SignalsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StocksRoute: StocksRoute,
  TahminTakibiRoute: TahminTakibiRoute,
  WatchlistRoute: WatchlistRoute,
  HisseSymbolRoute: HisseSymbolRoute,
  ApiPublicIngestMacroRoute: ApiPublicIngestMacroRoute,
  ApiPublicIngestNewsRoute: ApiPublicIngestNewsRoute,
  ApiPublicIngestOhlcRoute: ApiPublicIngestOhlcRoute,
  ApiPublicLiveMoversRoute: ApiPublicLiveMoversRoute,
  ApiPublicPredictionsRoute: ApiPublicPredictionsRoute,
  ApiPublicHooksDailyAuditRoute: ApiPublicHooksDailyAuditRoute,
  ApiPublicHooksWeeklyRetrainRoute: ApiPublicHooksWeeklyRetrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
