/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as FeatureImportanceRouteImport } from './routes/feature-importance'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as AiPatternsRouteImport } from './routes/ai-patterns'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureImportanceRoute = FeatureImportanceRouteImport.update({
  id: '/feature-importance',
  path: '/feature-importance',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPatternsRoute = AiPatternsRouteImport.update({
  id: '/ai-patterns',
  path: '/ai-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-patterns': typeof AiPatternsRoute
  '/coverage': typeof CoverageRoute
  '/events': typeof EventsRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/methodology': typeof MethodologyRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-patterns': typeof AiPatternsRoute
  '/coverage': typeof CoverageRoute
  '/events': typeof EventsRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/methodology': typeof MethodologyRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-patterns': typeof AiPatternsRoute
  '/coverage': typeof CoverageRoute
  '/events': typeof EventsRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/methodology': typeof MethodologyRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-patterns'
    | '/coverage'
    | '/events'
    | '/feature-importance'
    | '/methodology'
    | '/signals'
    | '/sitemap.xml'
    | '/stocks'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-patterns'
    | '/coverage'
    | '/events'
    | '/feature-importance'
    | '/methodology'
    | '/signals'
    | '/sitemap.xml'
    | '/stocks'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/ai-patterns'
    | '/coverage'
    | '/events'
    | '/feature-importance'
    | '/methodology'
    | '/signals'
    | '/sitemap.xml'
    | '/stocks'
    | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPatternsRoute: typeof AiPatternsRoute
  CoverageRoute: typeof CoverageRoute
  EventsRoute: typeof EventsRoute
  FeatureImportanceRoute: typeof FeatureImportanceRoute
  MethodologyRoute: typeof MethodologyRoute
  SignalsRoute: typeof SignalsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StocksRoute: typeof StocksRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-importance': {
      id: '/feature-importance'
      path: '/feature-importance'
      fullPath: '/feature-importance'
      preLoaderRoute: typeof FeatureImportanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-patterns': {
      id: '/ai-patterns'
      path: '/ai-patterns'
      fullPath: '/ai-patterns'
      preLoaderRoute: typeof AiPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPatternsRoute: AiPatternsRoute,
  CoverageRoute: CoverageRoute,
  EventsRoute: EventsRoute,
  FeatureImportanceRoute: FeatureImportanceRoute,
  MethodologyRoute: MethodologyRoute,
  SignalsRoute: SignalsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StocksRoute: StocksRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
