/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TahminTakibiRouteImport } from './routes/tahmin-takibi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ModelHealthRouteImport } from './routes/model-health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HisseSymbolRouteImport } from './routes/hisse.$symbol'
import { Route as ApiPublicPredictionsRouteImport } from './routes/api/public/predictions'
import { Route as ApiPublicLiveMoversRouteImport } from './routes/api/public/live-movers'
import { Route as ApiPublicIngestOhlcRouteImport } from './routes/api/public/ingest-ohlc'
import { Route as ApiPublicIngestNewsRouteImport } from './routes/api/public/ingest-news'
import { Route as ApiPublicIngestMacroRouteImport } from './routes/api/public/ingest-macro'
import { Route as ApiPublicHooksWeeklyRetrainRouteImport } from './routes/api/public/hooks/weekly-retrain'
import { Route as ApiPublicHooksDailyAuditRouteImport } from './routes/api/public/hooks/daily-audit'

const TahminTakibiRoute = TahminTakibiRouteImport.update({
  id: '/tahmin-takibi',
  path: '/tahmin-takibi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelHealthRoute = ModelHealthRouteImport.update({
  id: '/model-health',
  path: '/model-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HisseSymbolRoute = HisseSymbolRouteImport.update({
  id: '/hisse/$symbol',
  path: '/hisse/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPredictionsRoute = ApiPublicPredictionsRouteImport.update({
  id: '/api/public/predictions',
  path: '/api/public/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveMoversRoute = ApiPublicLiveMoversRouteImport.update({
  id: '/api/public/live-movers',
  path: '/api/public/live-movers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestOhlcRoute = ApiPublicIngestOhlcRouteImport.update({
  id: '/api/public/ingest-ohlc',
  path: '/api/public/ingest-ohlc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestNewsRoute = ApiPublicIngestNewsRouteImport.update({
  id: '/api/public/ingest-news',
  path: '/api/public/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestMacroRoute = ApiPublicIngestMacroRouteImport.update({
  id: '/api/public/ingest-macro',
  path: '/api/public/ingest-macro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyRetrainRoute =
  ApiPublicHooksWeeklyRetrainRouteImport.update({
    id: '/api/public/hooks/weekly-retrain',
    path: '/api/public/hooks/weekly-retrain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyAuditRoute =
  ApiPublicHooksDailyAuditRouteImport.update({
    id: '/api/public/hooks/daily-audit',
    path: '/api/public/hooks/daily-audit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/model-health': typeof ModelHealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tahmin-takibi': typeof TahminTakibiRoute
  '/hisse/$symbol': typeof HisseSymbolRoute
  '/api/public/ingest-macro': typeof ApiPublicIngestMacroRoute
  '/api/public/ingest-news': typeof ApiPublicIngestNewsRoute
  '/api/public/ingest-ohlc': typeof ApiPublicIngestOhlcRoute
  '/api/public/live-movers': typeof ApiPublicLiveMoversRoute
  '/api/public/predictions': typeof ApiPublicPredictionsRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/weekly-retrain': typeof ApiPublicHooksWeeklyRetrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/model-health': typeof ModelHealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tahmin-takibi': typeof TahminTakibiRoute
  '/hisse/$symbol': typeof HisseSymbolRoute
  '/api/public/ingest-macro': typeof ApiPublicIngestMacroRoute
  '/api/public/ingest-news': typeof ApiPublicIngestNewsRoute
  '/api/public/ingest-ohlc': typeof ApiPublicIngestOhlcRoute
  '/api/public/live-movers': typeof ApiPublicLiveMoversRoute
  '/api/public/predictions': typeof ApiPublicPredictionsRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/weekly-retrain': typeof ApiPublicHooksWeeklyRetrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/model-health': typeof ModelHealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tahmin-takibi': typeof TahminTakibiRoute
  '/hisse/$symbol': typeof HisseSymbolRoute
  '/api/public/ingest-macro': typeof ApiPublicIngestMacroRoute
  '/api/public/ingest-news': typeof ApiPublicIngestNewsRoute
  '/api/public/ingest-ohlc': typeof ApiPublicIngestOhlcRoute
  '/api/public/live-movers': typeof ApiPublicLiveMoversRoute
  '/api/public/predictions': typeof ApiPublicPredictionsRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/weekly-retrain': typeof ApiPublicHooksWeeklyRetrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/model-health'
    | '/sitemap.xml'
    | '/tahmin-takibi'
    | '/hisse/$symbol'
    | '/api/public/ingest-macro'
    | '/api/public/ingest-news'
    | '/api/public/ingest-ohlc'
    | '/api/public/live-movers'
    | '/api/public/predictions'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/weekly-retrain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/model-health'
    | '/sitemap.xml'
    | '/tahmin-takibi'
    | '/hisse/$symbol'
    | '/api/public/ingest-macro'
    | '/api/public/ingest-news'
    | '/api/public/ingest-ohlc'
    | '/api/public/live-movers'
    | '/api/public/predictions'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/weekly-retrain'
  id:
    | '__root__'
    | '/'
    | '/model-health'
    | '/sitemap.xml'
    | '/tahmin-takibi'
    | '/hisse/$symbol'
    | '/api/public/ingest-macro'
    | '/api/public/ingest-news'
    | '/api/public/ingest-ohlc'
    | '/api/public/live-movers'
    | '/api/public/predictions'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/weekly-retrain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelHealthRoute: typeof ModelHealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TahminTakibiRoute: typeof TahminTakibiRoute
  HisseSymbolRoute: typeof HisseSymbolRoute
  ApiPublicIngestMacroRoute: typeof ApiPublicIngestMacroRoute
  ApiPublicIngestNewsRoute: typeof ApiPublicIngestNewsRoute
  ApiPublicIngestOhlcRoute: typeof ApiPublicIngestOhlcRoute
  ApiPublicLiveMoversRoute: typeof ApiPublicLiveMoversRoute
  ApiPublicPredictionsRoute: typeof ApiPublicPredictionsRoute
  ApiPublicHooksDailyAuditRoute: typeof ApiPublicHooksDailyAuditRoute
  ApiPublicHooksWeeklyRetrainRoute: typeof ApiPublicHooksWeeklyRetrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tahmin-takibi': {
      id: '/tahmin-takibi'
      path: '/tahmin-takibi'
      fullPath: '/tahmin-takibi'
      preLoaderRoute: typeof TahminTakibiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-health': {
      id: '/model-health'
      path: '/model-health'
      fullPath: '/model-health'
      preLoaderRoute: typeof ModelHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisse/$symbol': {
      id: '/hisse/$symbol'
      path: '/hisse/$symbol'
      fullPath: '/hisse/$symbol'
      preLoaderRoute: typeof HisseSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/predictions': {
      id: '/api/public/predictions'
      path: '/api/public/predictions'
      fullPath: '/api/public/predictions'
      preLoaderRoute: typeof ApiPublicPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-movers': {
      id: '/api/public/live-movers'
      path: '/api/public/live-movers'
      fullPath: '/api/public/live-movers'
      preLoaderRoute: typeof ApiPublicLiveMoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-ohlc': {
      id: '/api/public/ingest-ohlc'
      path: '/api/public/ingest-ohlc'
      fullPath: '/api/public/ingest-ohlc'
      preLoaderRoute: typeof ApiPublicIngestOhlcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-news': {
      id: '/api/public/ingest-news'
      path: '/api/public/ingest-news'
      fullPath: '/api/public/ingest-news'
      preLoaderRoute: typeof ApiPublicIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-macro': {
      id: '/api/public/ingest-macro'
      path: '/api/public/ingest-macro'
      fullPath: '/api/public/ingest-macro'
      preLoaderRoute: typeof ApiPublicIngestMacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-retrain': {
      id: '/api/public/hooks/weekly-retrain'
      path: '/api/public/hooks/weekly-retrain'
      fullPath: '/api/public/hooks/weekly-retrain'
      preLoaderRoute: typeof ApiPublicHooksWeeklyRetrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-audit': {
      id: '/api/public/hooks/daily-audit'
      path: '/api/public/hooks/daily-audit'
      fullPath: '/api/public/hooks/daily-audit'
      preLoaderRoute: typeof ApiPublicHooksDailyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelHealthRoute: ModelHealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TahminTakibiRoute: TahminTakibiRoute,
  HisseSymbolRoute: HisseSymbolRoute,
  ApiPublicIngestMacroRoute: ApiPublicIngestMacroRoute,
  ApiPublicIngestNewsRoute: ApiPublicIngestNewsRoute,
  ApiPublicIngestOhlcRoute: ApiPublicIngestOhlcRoute,
  ApiPublicLiveMoversRoute: ApiPublicLiveMoversRoute,
  ApiPublicPredictionsRoute: ApiPublicPredictionsRoute,
  ApiPublicHooksDailyAuditRoute: ApiPublicHooksDailyAuditRoute,
  ApiPublicHooksWeeklyRetrainRoute: ApiPublicHooksWeeklyRetrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
